#ifndef __CMDQ_ENGINE_H__
#define __CMDQ_ENGINE_H__

typedef enum CMDQ_ENG_ENUM {
	/* ISP */
	CMDQ_ENG_ISP_IMGI = 0,
	CMDQ_ENG_ISP_IMGO,	/* 1 */
	CMDQ_ENG_ISP_IMG2O,	/* 2 */

	/* MDP */
	CMDQ_ENG_MDP_CAMIN,	/* 3 */
	CMDQ_ENG_MDP_RDMA0,	/* 4 */
	CMDQ_ENG_MDP_CCORR0,	/* 5 */
	CMDQ_ENG_MDP_RSZ0,	/* 6 */
	CMDQ_ENG_MDP_RSZ1,	/* 7 */
	CMDQ_ENG_MDP_TDSHP0,	/* 8 */
	CMDQ_ENG_MDP_COLOR0,	/* 9 */
	CMDQ_ENG_MDP_WROT0,	/* 10 */
	CMDQ_ENG_MDP_WDMA,	/* 11 */


	/* JPEG & VENC */
	CMDQ_ENG_JPEG_ENC,	/* 12 */
	CMDQ_ENG_VIDEO_ENC,	/* 13 */
	CMDQ_ENG_JPEG_DEC,	/* 14 */
	CMDQ_ENG_JPEG_REMDC,	/* 15 */

	/* DISP */
	CMDQ_ENG_DISP_UFOE,	/* 16 */
	CMDQ_ENG_DISP_AAL,	/* 17 */
	CMDQ_ENG_DISP_COLOR0,	/* 18 */
	CMDQ_ENG_DISP_RDMA0,	/* 19 */
	CMDQ_ENG_DISP_RDMA1,	/* 20 */
	CMDQ_ENG_DISP_WDMA0,	/* 21 */
	CMDQ_ENG_DISP_WDMA1,	/* 22 */
	CMDQ_ENG_DISP_OVL0,	/* 23 */
	CMDQ_ENG_DISP_OVL1,	/* 24 */
	CMDQ_ENG_DISP_OVL2,	/* 25 */
	CMDQ_ENG_DISP_GAMMA,	/* 26 */
	CMDQ_ENG_DISP_DSI0_VDO,	/* 27 */
	CMDQ_ENG_DISP_DSI0_CMD,	/* 28 */
	CMDQ_ENG_DISP_DSI0,	/* 29 */
	CMDQ_ENG_DISP_DPI,	/* 30 */
	CMDQ_ENG_DISP_2L_OVL0,	/* 31 */
	CMDQ_ENG_DISP_2L_OVL1,	/* 32 */
	CMDQ_ENG_DISP_2L_OVL2,	/* 33 */

	/* DPE */
	CMDQ_ENG_DPE,		/* 34 */
	CMDQ_ENG_RSC,		/* 35 */
	CMDQ_ENG_GEPF,		/* 36 */
	CMDQ_ENG_EAF,		/* 37 */

	/* ISP sec */
	CMDQ_ENG_ISP_VIPI,      /* 38 */
	CMDQ_ENG_ISP_LCEI,      /* 39 */
	CMDQ_ENG_ISP_IMG3O,     /* 40 */

	/* temp: CMDQ internal usage */
	CMDQ_ENG_CMDQ,		/* 41 */
	CMDQ_ENG_DISP_MUTEX,	/* 42 */
	CMDQ_ENG_MMSYS_CONFIG,	/* 43 */

	/* Dummy Engine */
	CMDQ_ENG_MDP_TDSHP1,	/* 44 */
	CMDQ_ENG_MDP_MOUT0,	/* 45 */
	CMDQ_ENG_MDP_MOUT1,	/* 46 */
	CMDQ_ENG_MDP_RDMA1,	/* 47 */
	CMDQ_ENG_MDP_RSZ2,	/* 48 */
	CMDQ_ENG_MDP_WROT1,	/* 49 */
	CMDQ_ENG_DISP_COLOR1,	/* 50 */
	CMDQ_ENG_DISP_RDMA2,	/* 51 */
	CMDQ_ENG_DISP_MERGE,	/* 52 */
	CMDQ_ENG_DISP_SPLIT0,	/* 53 */
	CMDQ_ENG_DISP_SPLIT1,	/* 54 */
	CMDQ_ENG_DISP_DSI1_VDO,	/* 55 */
	CMDQ_ENG_DISP_DSI1_CMD,	/* 56 */
	CMDQ_ENG_DISP_DSI1,	/* 57 */

	CMDQ_ENG_INORDER,	/* 58 */

	CMDQ_MAX_ENGINE_COUNT	/* ALWAYS keep at the end */
} CMDQ_ENG_ENUM;

enum MDP_ENG_BASE {
  ENGBASE_MMSYS_CONFIG,
  ENGBASE_MDP_RDMA0,
  ENGBASE_MDP_CCORR0,
  ENGBASE_MDP_RSZ0,
  ENGBASE_MDP_RSZ1,
  ENGBASE_MDP_WDMA,
  ENGBASE_MDP_WROT0,
  ENGBASE_MDP_TDSHP0,
  ENGBASE_MDP_COLOR0,
  ENGBASE_MMSYS_MUTEX,
  ENGBASE_ISP_CAMSYS,
  ENGBASE_ISP_CAM,
  ENGBASE_ISP_CAM_DMA,
  ENGBASE_IMGSYS,
  ENGBASE_ISP_DIP1,
  ENGBASE_COUNT
};
#endif				/* __CMDQ_ENGINE_H__ */
